# vim: syntax=ruby filetype=ruby

# System tools
brew 'gettext'
brew 'coreutils'
brew 'pstree'
brew 'findutils'
brew 'htop'
brew 'gnupg'
brew 'gnu-tar'
brew 'gnu-which'
brew 'gnu-sed'
brew 'grep'
brew 'less'
brew 'tree'
brew 'screen'
brew 'shfmt'
brew 'jump'
brew 'eza'
brew 'ast-grep'
brew 'stow'

# Util
brew 'pngquant'
brew 'zopfli'

# Development & Tools
cask 'ghostty'
cask 'jetbrains-toolbox'
cask 'visual-studio-code'
brew 'neovim'
brew 'bash'
brew 'bash-completion'
brew 'zsh'
brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'bat'
brew 'colordiff'
brew 'pinentry-mac'
brew 'diff-so-fancy'
brew 'git'
brew 'git-delta'
brew 'git-crypt'
brew 'git-interactive-rebase-tool'
brew 'git-lfs'
brew 'lazygit'
brew 'hub'
brew 'ripgrep'
brew 'fd'
brew 'tldr'
brew 'shellcheck'
brew 'fzf'
brew 'jq'
brew 'direnv'
brew 'watch'
brew 'universal-ctags'
brew 'curl'
brew 'shellcheck'
brew 'tmux'
brew 'gh'
brew 'wget'
brew 'editorconfig'
brew 'ghostscript'
brew 'imagemagick'
brew 'tectonic'
brew 'luajit'
brew 'markdownlint-cli2'
brew 'mermaid-cli'

# Languages
brew 'go'
brew 'fnm'
brew 'rust'
cask 'corretto'
brew 'luarocks'
brew 'golangci-lint'

# Container
cask 'docker-desktop'

# Tooling
brew 'aria2'
brew 'rclone'

# Desktop
cask 'rectangle'
cask 'monitorcontrol'
cask 'google-chrome'
cask 'open-in-code'
cask 'discord'
cask 'iina'
cask 'anki'
cask 'obsidian'
cask 'font-hack-nerd-font'
cask 'whatsapp'
cask 'telegram'
cask 'shottr'
cask 'google-drive'
cask 'signal'
cask 'maccy'
